workflows:
  macos_vps_247:
    name: "macOS VPS Loop Runner Auto Restart"
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        LOOP_FILE: "loop.py"
        PERSIST_PATH: "/Users/builder/.persist_data"
        MAX_HOURS: "0.01"  # test nhanh ~36 giây, đổi lại 1.8 khi chạy thật
        CM_API_TOKEN: Encrypted(THAY_TOKEN_TAI_DAY)
        CM_APP_ID: "68e55d53dd7c70195324202b"
        CM_WORKFLOW_ID: "macos_vps_247"
      xcode: latest

    triggering:
      events:
        - push

    scripts:
      - name: Setup environment
        script: |
          echo "=== Setup Python and folders ==="
          brew install python@3.12 || echo "Python already available"
          mkdir -p $PERSIST_PATH

      - name: Create loop script
        script: |
          cat > $LOOP_FILE <<'PYCODE'
          import os, time, datetime, json, subprocess

          DATA_PATH = os.environ.get("PERSIST_PATH", "/Users/builder/.persist_data")
          LOG_FILE = os.path.join(DATA_PATH, "loop_log.json")
          MAX_HOURS = float(os.environ.get("MAX_HOURS", "0.01"))
          RUNTIME_LIMIT = MAX_HOURS * 3600

          print("VPS Loop Runner started...")
          start_time = time.time()
          os.makedirs(DATA_PATH, exist_ok=True)

          try:
              while True:
                  uptime = time.time() - start_time
                  now = datetime.datetime.now().isoformat()
                  remaining = RUNTIME_LIMIT - uptime
                  print(f"[{now}] Running {uptime/3600:.2f}h (remaining {remaining/60:.1f} min).")

                  if int(uptime) % 300 < 60:
                      with open(LOG_FILE, "a") as f:
                          f.write(json.dumps({"time": now, "uptime_hr": uptime/3600}) + "\n")

                  if uptime >= RUNTIME_LIMIT:
                      print(f"Restarting after {MAX_HOURS}h...")
                      break

                  time.sleep(10)  # kiểm tra nhanh hơn

          except Exception as e:
              print(f"Loop error: {e}")

          token = os.environ.get("CM_API_TOKEN")
          app_id = os.environ.get("CM_APP_ID")
          workflow_id = os.environ.get("CM_WORKFLOW_ID", "macos_vps_247")

          if token and app_id:
              print("Sending restart request to Codemagic API...")
              payload = json.dumps({"appId": app_id, "workflowId": workflow_id})
              cmd = [
                  "curl", "-sS", "-X", "POST",
                  "https://api.codemagic.io/builds",
                  "-H", "Content-Type: application/json",
                  "-H", f"x-auth-token: {token}",
                  "-d", payload
              ]
              result = subprocess.run(cmd, capture_output=True, text=True)
              print("API response:", result.stdout or result.stderr)
          else:
              print("Missing CM_API_TOKEN or CM_APP_ID - cannot restart.")
          PYCODE

      - name: Run loop
        script: |
          echo "=== Starting VPS loop ==="
          python3 $LOOP_FILE
